import = ["~/.config/alacritty/catppuccin-mocha.toml" ]

[window]
padding = {x = 5, y = 5}
opacity = 1

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "BoldItalic" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }

